[package]
name = "check-if-email-exists-cli"
version = "0.8.20"
default-run = "check_if_email_exists"
edition = "2018"
description = "Check if an email address exists without sending any email."
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
license = "AGPL-3.0"
publish = false

[[bin]]
name = "check_if_email_exists"
path = "src/main.rs"

[dependencies]
check-if-email-exists = { path = "./core" }
clap = "3.0.0-beta.2"
env_logger = "0.8.3"
once_cell = "1.5.2"
serde = "1.0.123"
serde_json = "1.0.61"

[dependencies.hyper]
version = "0.14.4"
features = ["full"]

[dependencies.tokio]
version = "1.1.1"
features = ["macros", "net", "io-util", "rt-multi-thread"]

[profile.release]
lto = true

[workspace]
members = [
	"core",
	"test_suite"
]
