[package]
name = "check-if-email-exists-cli"
version = "0.8.19"
default-run = "check_if_email_exists"
edition = "2018"
description = "Check if an email address exists without sending any email."
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
license = "AGPL-3.0"
publish = false

[[bin]]
name = "check_if_email_exists"
path = "src/main.rs"

[dependencies]
check-if-email-exists = { path = "./core" }
clap = "3.0.0-beta.2"
env_logger = "0.8"
hyper = "0.14"
once_cell = "1.5"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "io-util"] }

[profile.release]
lto = true

[workspace]
members = [
	"core",
	"test_suite"
]
