[package]
name = "check_if_email_exists_cli"
version = "0.4.0"
edition = "2018"
publish = false

[[bin]]
name = "check_if_email_exists"
path = "src/main.rs"

[dependencies]
check_if_email_exists = { path = "core" }
clap = { version = "2.32", features = ["yaml"] }
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"

[workspace]
members = [
	"core",
	"serverless",
	"test_suite"
]
