[package]
name = "reacher_backend"
version = "0.5.0"
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
async-smtp = "0.6"
check-if-email-exists = { path = "../core", features = ["headless"] }
dotenv = "0.15.0"
futures = { version = "0.3.30", optional = true }
futures-lite = { version = "2.1.0", optional = true }
lapin = { version = "2.3.1", optional = true }
openssl = { version = "0.10.62", features = ["vendored"] }
reqwest = { version = "0.11.23", features = ["json"], optional = true }
sentry = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "migrate",
], optional = true }
tokio = { version = "1.35", features = ["macros"] }
tokio-executor-trait = { version = "2.1.1", optional = true }
tokio-reactor-trait = { version = "1.1.0", optional = true }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
warp = "0.3"

[features]
worker = [
    "futures",
    "futures-lite",
    "lapin",
    "reqwest",
    "tokio-executor-trait",
    "tokio-reactor-trait",
]

postgres = ["sqlx"]
