[package]
name = "reacher_backend"
version = "0.4.0"
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
async-smtp = "0.6"
check-if-email-exists = { path = "../core", features = ["headless"] }
csv = "1.1.6"
dotenv = "0.15.0"
env_logger = "0.10"
log = "0.4"
openssl = { version = "0.10.45", features = ["vendored"] }
sentry = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "postgres", "uuid", "chrono", "json", "offline", "migrate" ] }
sqlxmq = "0.4"
tokio = { version = "1.25", features = ["macros"] }
uuid = "1.3"
warp = "0.3"
