[package]
name = "check-if-email-exists-test-suite"
version = "0.8.24"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
serde = "1.0.142"
serde_json = "1.0.82"
tokio = { version = "1.16.1", features = ["rt"] }
