[package]
name = "check-if-email-exists-test-suite"
version = "0.8.22"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { path = "../core" }
serde = "1.0.125"
serde_json = "1.0.64"
tokio = { version = "1.6.0", features = ["rt"] }
