name: tag

on:
  push:
    tags:
      - "backend/v*.*.*"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set GITHUB_TAG arg
        id: vars
        run: echo ::set-output name=GITHUB_TAG::${GITHUB_REF:18} # Remove /refs/head/backend/
      - name: Print version
        run: echo "Publishing reacherhq/backend:${{ steps.vars.outputs.GITHUB_TAG }}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: reacherhq/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ steps.vars.outputs.GITHUB_TAG }}"
